// src/components/LegalModal.jsx
// ─────────────────────────────────────────────────────────────────────────────
// Lightweight modal for Privacy Policy, Terms of Service, and Contact page.
// Matches TennisVantage dark design system exactly.
// ─────────────────────────────────────────────────────────────────────────────
import { useEffect } from 'react';

const CONTENT = {
  privacy: {
    title: 'Privacy Policy',
    icon: '🔒',
    lastUpdated: 'March 2025',
    sections: [
      {
        heading: 'Overview',
        body: 'TennisVantage ("we", "our", or "us") is a university project created for educational purposes. We are committed to being transparent about the limited data we collect and how it is used.',
      },
      {
        heading: 'Data We Collect',
        body: null,
        bullets: [
          'Email address and display name — collected when you create an account via Supabase Auth',
          'OAuth data — if you sign in with Google, we receive your public profile (name, email, avatar)',
          'Favourite players list — stored in your profile in our Supabase database',
          'Usage data — Supabase and Vercel may collect anonymised analytics (page views, function invocations)',
        ],
      },
      {
        heading: 'Data We Do NOT Collect',
        body: null,
        bullets: [
          'Payment information of any kind — TennisVantage is free and has no payment processing',
          'Precise location data',
          'Device identifiers or advertising IDs',
          'Any data sold or shared with third-party advertisers',
        ],
      },
      {
        heading: 'How We Use Your Data',
        body: 'Your email is used solely for authentication. Your profile data (name, avatar, favourite players) is used to personalise your experience within the app. We do not send marketing emails.',
      },
      {
        heading: 'Third-Party Services',
        body: null,
        bullets: [
          'Supabase — database, authentication, and file storage (supabase.com/privacy)',
          'Vercel — hosting and serverless functions (vercel.com/legal/privacy-policy)',
          'Google OAuth — optional sign-in only; governed by Google\'s Privacy Policy',
          'RapidAPI (Tennis API) — live match data; we do not share your data with them',
          'Google Gemini — AI predictions; only anonymised match data is sent, never your personal data',
        ],
      },
      {
        heading: 'Data Retention & Deletion',
        body: 'You may delete your account at any time by contacting us. Upon deletion, your profile and associated data will be permanently removed from our database within 30 days.',
      },
      {
        heading: 'Cookies',
        body: 'We use only essential cookies required for authentication (Supabase session token stored in localStorage). We do not use tracking or advertising cookies.',
      },
      {
        heading: 'Contact',
        body: 'For any privacy-related questions, please use the Contact page or email us at the address listed there.',
      },
    ],
  },

  terms: {
    title: 'Terms of Service',
    icon: '📄',
    lastUpdated: 'March 2025',
    sections: [
      {
        heading: 'About TennisVantage',
        body: 'TennisVantage is a university final-year project ("završni rad") created for educational purposes at Elektrotehnička škola Split. It is provided free of charge with no commercial intent.',
      },
      {
        heading: 'Acceptance of Terms',
        body: 'By creating an account or using TennisVantage, you agree to these terms. If you do not agree, please do not use the service.',
      },
      {
        heading: 'Permitted Use',
        body: null,
        bullets: [
          'You may use TennisVantage for personal, non-commercial purposes',
          'You must be at least 13 years old to create an account',
          'You are responsible for maintaining the security of your account credentials',
          'You agree not to attempt to reverse-engineer, scrape, or abuse the service',
        ],
      },
      {
        heading: 'AI Predictions Disclaimer',
        body: 'All match predictions generated by TennisVantage are produced by an AI model (Google Gemini) and are for entertainment and informational purposes only. They do not constitute professional sports advice, gambling recommendations, or financial guidance. Predictions may be inaccurate. Never make financial decisions based on AI predictions.',
      },
      {
        heading: 'Data Accuracy',
        body: 'Live match data is sourced from third-party APIs and may contain errors or delays. Rankings, scores, and player statistics are provided "as-is" with no warranty of accuracy or completeness.',
      },
      {
        heading: 'Intellectual Property',
        body: 'The TennisVantage codebase, design, and written content are the work of the project author. Tennis player names, tournament names, and related trademarks belong to their respective owners (ATP, WTA, ITF, etc.). TennisVantage is not affiliated with or endorsed by any tennis organisation.',
      },
      {
        heading: 'Limitation of Liability',
        body: 'TennisVantage is provided "as is" without warranty of any kind. To the fullest extent permitted by law, we are not liable for any damages arising from your use of the service, including but not limited to data loss, service interruptions, or inaccurate predictions.',
      },
      {
        heading: 'Service Availability',
        body: 'As a university project, TennisVantage may be taken offline or modified at any time without notice. We do not guarantee continuous availability of the service.',
      },
      {
        heading: 'Changes to Terms',
        body: 'We may update these terms at any time. Continued use of the service after changes are posted constitutes acceptance of the new terms.',
      },
    ],
  },

  contact: {
    title: 'Contact',
    icon: '✉️',
    lastUpdated: null,
    sections: [
      {
        heading: 'About This Project',
        body: 'TennisVantage is a final-year school project (završni rad) developed at Elektrotehnička škola Split, Croatia. It was built as a full-stack web application demonstrating modern web development with React, Supabase, and AI integration.',
      },
      {
        heading: 'Project Author',
        body: null,
        card: {
          name: 'Vito',
          school: 'Elektrotehnička škola Split',
          programme: 'Tehničar za računalstvo',
          mentor: 'Marin Ivandić',
          year: '2024 / 2025',
        },
      },
      {
        heading: 'Get in Touch',
        body: 'This project is for educational evaluation purposes. For questions about the project, technical feedback, or academic enquiries, please reach out via the school.',
      },
      {
        heading: 'Tech Stack',
        body: null,
        bullets: [
          'Frontend: React 18 + Vite, deployed on Vercel',
          'Backend: Supabase (PostgreSQL + Edge Functions + Auth)',
          'Data: RapidAPI Tennis API (live ATP/WTA data)',
          'AI: Google Gemini 2.5 Flash (predictions + chat)',
          'Flags: flagcdn.com',
        ],
      },
      {
        heading: 'Bug Reports & Feedback',
        body: 'If you notice incorrect data, broken functionality, or have suggestions for improvement, your feedback is welcome and appreciated as part of the project evaluation process.',
      },
    ],
  },
};

export default function LegalModal({ page, onClose }) {
  const content = CONTENT[page];

  // ESC to close
  useEffect(() => {
    const fn = (e) => { if (e.key === 'Escape') onClose(); };
    window.addEventListener('keydown', fn);
    return () => window.removeEventListener('keydown', fn);
  }, [onClose]);

  // Lock body scroll
  useEffect(() => {
    const scrollY = window.scrollY;
    document.body.style.overflow  = 'hidden';
    document.body.style.position  = 'fixed';
    document.body.style.top       = `-${scrollY}px`;
    document.body.style.left      = '0';
    document.body.style.right     = '0';
    return () => {
      document.body.style.overflow  = '';
      document.body.style.position  = '';
      document.body.style.top       = '';
      document.body.style.left      = '';
      document.body.style.right     = '';
      window.scrollTo(0, scrollY);
    };
  }, []);

  if (!content) return null;

  return (
    <>
      {/* Backdrop */}
      <div
        onClick={onClose}
        style={{
          position: 'fixed', inset: 0, zIndex: 1000,
          background: 'rgba(0,0,0,0.75)',
          backdropFilter: 'blur(6px)',
          WebkitBackdropFilter: 'blur(6px)',
          animation: 'tv-fade-in 0.2s ease',
        }}
      />

      {/* Modal */}
      <div style={{
        position: 'fixed',
        top: '50%', left: '50%',
        transform: 'translate(-50%, -50%)',
        zIndex: 1001,
        width: 'min(680px, calc(100vw - 32px))',
        maxHeight: '85dvh',
        display: 'flex',
        flexDirection: 'column',
        background: 'var(--bg-card)',
        border: '1px solid var(--border-md)',
        borderRadius: 'var(--radius-lg)',
        boxShadow: '0 40px 100px rgba(0,0,0,0.7), 0 0 60px rgba(159,239,102,0.04)',
        animation: 'tv-pop 0.3s cubic-bezier(0.34,1.56,0.64,1) both',
        overflow: 'hidden',
      }}>

        {/* Sticky header */}
        <div style={{
          display: 'flex', alignItems: 'center', justifyContent: 'space-between',
          padding: '20px 24px',
          borderBottom: '1px solid var(--border)',
          flexShrink: 0,
          background: 'var(--bg-card)',
        }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
            <span style={{ fontSize: '24px' }}>{content.icon}</span>
            <div>
              <h2 style={{
                fontFamily: 'var(--font-display)', fontWeight: 800,
                fontSize: 'clamp(18px, 3vw, 22px)',
                letterSpacing: '-0.02em', margin: 0,
              }}>
                {content.title}
              </h2>
              {content.lastUpdated && (
                <p style={{ fontSize: '12px', color: 'var(--text-faint)', margin: '2px 0 0' }}>
                  Last updated: {content.lastUpdated}
                </p>
              )}
            </div>
          </div>
          <button
            onClick={onClose}
            style={{
              width: '36px', height: '36px', borderRadius: '50%',
              background: 'var(--bg-glass-md)', border: '1px solid var(--border)',
              color: 'var(--text-muted)', cursor: 'pointer', flexShrink: 0,
              display: 'flex', alignItems: 'center', justifyContent: 'center',
              fontSize: '18px', transition: 'var(--t)',
            }}
            onMouseEnter={e => { e.currentTarget.style.background = 'rgba(248,113,113,0.12)'; e.currentTarget.style.color = 'var(--red)'; e.currentTarget.style.borderColor = 'rgba(248,113,113,0.3)'; }}
            onMouseLeave={e => { e.currentTarget.style.background = 'var(--bg-glass-md)'; e.currentTarget.style.color = 'var(--text-muted)'; e.currentTarget.style.borderColor = 'var(--border)'; }}
          >
            ✕
          </button>
        </div>

        {/* Scrollable body */}
        <div style={{
          overflowY: 'auto',
          padding: '24px',
          display: 'flex',
          flexDirection: 'column',
          gap: '24px',
          WebkitOverflowScrolling: 'touch',
          overscrollBehavior: 'contain',
        }}>
          {content.sections.map((section, i) => (
            <div key={i}>
              <h3 style={{
                fontFamily: 'var(--font-display)', fontWeight: 700,
                fontSize: '15px', color: 'var(--lime)',
                letterSpacing: '-0.01em', marginBottom: '10px',
                display: 'flex', alignItems: 'center', gap: '8px',
              }}>
                <span style={{
                  width: '4px', height: '16px', borderRadius: '2px',
                  background: 'var(--lime)', flexShrink: 0, display: 'inline-block',
                }} />
                {section.heading}
              </h3>

              {/* Plain paragraph */}
              {section.body && (
                <p style={{
                  fontSize: '14px', color: 'var(--text-muted)',
                  lineHeight: 1.75, margin: 0,
                }}>
                  {section.body}
                </p>
              )}

              {/* Bullet list */}
              {section.bullets && (
                <ul style={{ listStyle: 'none', padding: 0, margin: 0, display: 'flex', flexDirection: 'column', gap: '8px' }}>
                  {section.bullets.map((b, j) => (
                    <li key={j} style={{
                      display: 'flex', alignItems: 'flex-start', gap: '10px',
                      fontSize: '14px', color: 'var(--text-muted)', lineHeight: 1.65,
                    }}>
                      <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="var(--lime)" strokeWidth="2.5" style={{ flexShrink: 0, marginTop: '4px' }}>
                        <polyline points="20 6 9 17 4 12" />
                      </svg>
                      {b}
                    </li>
                  ))}
                </ul>
              )}

              {/* Author card (Contact page) */}
              {section.card && (
                <div style={{
                  padding: '18px 20px',
                  background: 'rgba(159,239,102,0.06)',
                  border: '1px solid rgba(159,239,102,0.18)',
                  borderRadius: 'var(--radius)',
                  display: 'grid',
                  gridTemplateColumns: '1fr 1fr',
                  gap: '12px',
                }}>
                  {[
                    { label: 'Author',      value: section.card.name      },
                    { label: 'School',      value: section.card.school     },
                    { label: 'Programme',   value: section.card.programme  },
                    { label: 'Mentor',      value: section.card.mentor     },
                    { label: 'School Year', value: section.card.year       },
                  ].map(row => (
                    <div key={row.label}>
                      <p style={{ fontSize: '10px', fontWeight: 700, color: 'var(--text-faint)', textTransform: 'uppercase', letterSpacing: '0.08em', marginBottom: '3px' }}>
                        {row.label}
                      </p>
                      <p style={{ fontSize: '14px', fontWeight: 600, color: 'var(--text)', margin: 0 }}>
                        {row.value}
                      </p>
                    </div>
                  ))}
                </div>
              )}
            </div>
          ))}

          {/* Bottom padding for scroll breathing room */}
          <div style={{ height: '8px' }} />
        </div>
      </div>
    </>
  );
}